# Generated by Django 2.2.10 on 2020-03-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='height',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
